export const mockTransactions = [
  {
    id: 'ntTfe7gRlpn5jdFs',
    transactionDate: '2022-12-22T03:25:11.630Z',
    type: 'CREDIT',
    details: 'Cash Contest Cancelled',
    amount: 10,
    amountBonus: 0,
    status: 'COMPLETE',
    userId: 'ntTfe7gRlpn5jdFs',
    username: 'testuser',
  },
  {
    id: 'ethq8juazC7KtvgH',
    transactionDate: '2022-12-22T03:25:11.577Z',
    type: 'CREDIT',
    details: 'Win',
    amount: 25,
    amountBonus: 0,
    status: 'COMPLETE',
    userId: 'ntTfe7gRlpn5jdFs',
    username: 'testuser',
  },
  {
    id: 'UMI9tDWaT7xNtVHg',
    transactionDate: '2022-12-22T01:03:59.711Z',
    type: 'DEBIT',
    details: 'Place entry',
    amount: 10,
    amountBonus: 0,
    status: 'COMPLETE',
    userId: 'ntTfe7gRlpn5jdFs',
    username: 'testuser',
  },
  {
    id: 'wgbHYWZqSBtIctX8',
    transactionDate: '2022-12-21T05:27:23.935Z',
    type: 'DEBIT',
    details: 'Place entry',
    amount: 10,
    amountBonus: 0,
    status: 'COMPLETE',
    userId: 'ntTfe7gRlpn5jdFs',
    username: 'testuser',
  },
];
