import { contestCategoriesMock } from '~/components/Pages/Admin/ManageFreeSquarePromotion/__mocks__/contestCategoriesMock';

export const mockCards = [
  {
    id: '1',
    onClickLess: () => alert('clicked'),
    onClickMore: () => alert('clicked'),
    stat: 'Passing Yards',
    value: 99.5,
    gameInfo: 'LA@DEN',
    playerName: 'Patrick Mahomes',
    image: '/assets/images/dallas-goedert.png',
    playerPosition: 'QB',
    playerTeam: 'KC',
    freeSquare: {
      id: '1',
      discount: 98,
      pickCategories: contestCategoriesMock,
      maxStake: 25,
      freeEntryEnabled: false,
    },
  },
  {
    id: '2',
    onClickLess: () => alert('clicked'),
    onClickMore: () => alert('clicked'),
    stat: 'Passing Yards',
    value: 99.5,
    gameInfo: 'LA@DEN',
    playerName: 'Patrick Mahomes',
    image: '/assets/images/patrick-mahomes.png',
    playerPosition: 'QB',
    playerTeam: 'KC',
    freeSquare: null,
  },
  {
    id: '3',
    onClickLess: () => alert('clicked'),
    onClickMore: () => alert('clicked'),
    stat: 'Passing Yards',
    value: 99.5,
    gameInfo: 'LA@DEN',
    playerName: 'Patrick Mahomes',
    image: '/assets/images/tyrod-taylor.png',
    playerPosition: 'QB',
    playerTeam: 'KC',
    freeSquare: null,
  },
  {
    id: '4',
    onClickLess: () => alert('clicked'),
    onClickMore: () => alert('clicked'),
    stat: 'Passing Yards',
    value: 99.5,
    gameInfo: 'LA@DEN',
    playerName: 'Patrick Mahomes',
    image: '/assets/images/tyrod-taylor.png',
    playerPosition: 'QB',
    playerTeam: 'KC',
    freeSquare: null,
  },
];
