import { League, Status } from '@prisma/client';

export const tournamentEventOfferMock = {
  tournamentEvent: {
    id: 'a060eb83-d1ea-5940-b5fd-81c4408b9823',
    name: 'Golf 2nd Round Robin',
    league: League.GOLF,
    created_at: '2023-06-27T06:28:50.362Z',
    updated_at: '2023-06-27T06:29:27.552Z',
    Offers: [
      {
        gid: '96406579-3407-5076-a8a8-33347f340c20',
        league: League.GOLF,
        gamedate: '2023-06-27',
        epoch: 1687847486,
        start_utc: null,
        end_utc: null,
        inplay: false,
        status: Status.Scheduled,
        matchup: 'Golf 2nd Round Robin',
        gametime: '14:31:26',
        created_at: '2023-06-27T06:31:46.076Z',
        updated_at: '2023-06-27T06:31:46.076Z',
        homeTeamId: '7-nhl',
        awayTeamId: '7-nhl',
        manualEntry: true,
        tournamentEventId: 'a060eb83-d1ea-5940-b5fd-81c4408b9823',
        markets: [
          {
            id: '5bedd66d-e27b-5fd5-abb4-7dd9bda8afa2',
            sel_id: 1687847486,
            type: 'PP',
            category: 'Birdie',
            name: 'Vinnie Hinostroza',
            teamAbbrev: 'BUF',
            offline: false,
            spread: null,
            spread_odd: null,
            total: 2,
            over: 100,
            under: -100,
            moneyline: null,
            spread_bet: null,
            spread_cash: null,
            over_bet: null,
            under_bet: null,
            over_cash: null,
            under_cash: null,
            moneyline_bet: null,
            moneyline_cash: null,
            spread_result: 'Null',
            spread_stat: null,
            over_result: 'Null',
            under_result: 'Null',
            total_stat: null,
            moneyline_result: 'Null',
            moneyline_stat: null,
            offerId: '96406579-3407-5076-a8a8-33347f340c20',
            teamId: null,
            playerId: '1000-nhl',
            freeSquareId: null,
            created_at: '2023-06-27T06:31:46.076Z',
            updated_at: '2023-06-27T06:31:46.076Z',
            marketOverrideId: null,
            active: true,
            team: null,
            player: {
              id: '1000-nhl',
              name: 'Vinnie Hinostroza',
              position: 'C',
              teamid: '7-nhl',
              team: 'Buffalo Sabres',
              headshot: null,
              Team: {
                id: '7-nhl',
                name: 'Buffalo',
                code: 'BUF',
              },
            },
          },
        ],
      },
    ],
  },
  handleSaveTournamentEventOffer: () =>
    console.log('handleSaveTournamentEventOffer'),
  handleDeleteTournamentEventOffer: () =>
    console.log('handleDeleteTournamentEventOffer'),
  isLoading: false,
  teams: [],
  players: [],
  setPlayerFilterName: () => console.log('setPlayerFilterName'),
  playerIsLoading: false,
  setTeamFilterName: () => console.log('setTeamFilterName'),
  teamIsLoading: false,
  handleAddTeam: () => console.log('handleAddTeam'),
  handleAddPlayer: () => console.log('handleAddPlayer'),
};
