import { League, Status } from '@prisma/client';

export const tournamentEventMock = {
  data: [
    {
      id: 'a060eb83-d1ea-5940-b5fd-81c4408b9823',
      name: 'Golf 2nd Round Robin',
      league: League.GOLF,
      created_at: '2023-06-27T06:28:50.362Z',
      updated_at: '2023-06-27T06:29:27.552Z',
      Offers: [
        {
          gid: '96406579-3407-5076-a8a8-33347f340c20',
          league: League.GOLF,
          gamedate: '2023-06-27',
          epoch: 1687847486,
          start_utc: null,
          end_utc: null,
          inplay: false,
          status: Status.Scheduled,
          matchup: 'Golf 2nd Round Robin',
          gametime: '14:31:26',
          created_at: '2023-06-27T06:31:46.076Z',
          updated_at: '2023-06-27T06:31:46.076Z',
          homeTeamId: '7-nhl',
          awayTeamId: '7-nhl',
          manualEntry: true,
          tournamentEventId: 'a060eb83-d1ea-5940-b5fd-81c4408b9823',
          markets: [
            {
              id: '5bedd66d-e27b-5fd5-abb4-7dd9bda8afa2',
              sel_id: 1687847486,
              type: 'PP',
              category: 'Birdie',
              name: 'Vinnie Hinostroza',
              teamAbbrev: 'BUF',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 2,
              over: 100,
              under: -100,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: null,
              moneyline_result: 'Null',
              moneyline_stat: null,
              offerId: '96406579-3407-5076-a8a8-33347f340c20',
              teamId: null,
              playerId: '1000-nhl',
              freeSquareId: null,
              created_at: '2023-06-27T06:31:46.076Z',
              updated_at: '2023-06-27T06:31:46.076Z',
              marketOverrideId: null,
              active: true,
              team: null,
              player: {
                id: '1000-nhl',
                name: 'Vinnie Hinostroza',
                position: 'C',
                teamid: '7-nhl',
                team: 'Buffalo Sabres',
                headshot: null,
                Team: {
                  id: '7-nhl',
                  name: 'Buffalo',
                  code: 'BUF',
                },
              },
            },
          ],
        },
      ],
    },
    {
      id: 'cafc8095-1433-58e7-b9f5-9b76e1c27f21',
      name: 'Summer League',
      league: League.NBA,
      created_at: new Date('2023-06-23T11:48:25.317Z'),
      updated_at: new Date('2023-06-23T11:48:25.317Z'),
      Offers: [
        {
          gid: '8e34d62d-07c5-588e-8762-2d7957d741a4',
          league: League.NBA,
          gamedate: '2023-06-27',
          epoch: 1687847317,
          start_utc: null,
          end_utc: null,
          inplay: false,
          status: Status.Scheduled,
          matchup: 'Summer League',
          gametime: '14:28:37',
          created_at: new Date('2023-06-23T11:48:25.317Z'),
          updated_at: new Date('2023-06-23T11:48:25.317Z'),
          homeTeamId: '20-nba',
          awayTeamId: '20-nba',
          manualEntry: true,
          tournamentEventId: 'cafc8095-1433-58e7-b9f5-9b76e1c27f21',
          markets: [
            {
              id: '1558992d-1006-5b83-b7ac-fd52b2706d83',
              sel_id: 1687846142,
              type: 'PP',
              category: 'Assists',
              name: 'Chris Paul',
              teamAbbrev: 'PHX',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 10,
              over: 100,
              under: -100,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: 0,
              moneyline_result: 'Null',
              moneyline_stat: null,
              offerId: '8e34d62d-07c5-588e-8762-2d7957d741a4',
              teamId: null,
              playerId: '8030-nba',
              freeSquareId: null,
              created_at: '2023-06-27T06:09:26.856Z',
              updated_at: '2023-06-27T06:28:37.871Z',
              marketOverrideId: null,
              active: true,
              team: null,
              player: {
                id: '8030-nba',
                name: 'Chris Paul',
                position: 'G',
                teamid: '20-nba',
                team: 'Phoenix Suns',
                headshot: null,
                Team: {
                  id: '20-nba',
                  name: 'Phoenix',
                  code: 'PHX',
                },
              },
            },
          ],
        },
        {
          gid: '0ab635f8-af84-5a28-b592-452158e1b6b6',
          league: League.NBA,
          gamedate: '2023-06-27',
          epoch: 1687847324,
          start_utc: null,
          end_utc: null,
          inplay: false,
          status: Status.Scheduled,
          matchup: 'Summer League',
          gametime: '14:28:44',
          created_at: new Date('2023-06-23T11:48:25.317Z'),
          updated_at: new Date('2023-06-23T11:48:25.317Z'),
          homeTeamId: '11-nba',
          awayTeamId: '11-nba',
          manualEntry: true,
          tournamentEventId: 'cafc8095-1433-58e7-b9f5-9b76e1c27f21',
          markets: [
            {
              id: 'c4e7c438-9f9a-59cc-a1ab-d72ffcbb028c',
              sel_id: 1687846104,
              type: 'PP',
              category: 'Points',
              name: 'LeBron James',
              teamAbbrev: 'LAL',
              offline: false,
              spread: null,
              spread_odd: null,
              total: 46,
              over: 100,
              under: -100,
              moneyline: null,
              spread_bet: null,
              spread_cash: null,
              over_bet: null,
              under_bet: null,
              over_cash: null,
              under_cash: null,
              moneyline_bet: null,
              moneyline_cash: null,
              spread_result: 'Null',
              spread_stat: null,
              over_result: 'Null',
              under_result: 'Null',
              total_stat: 0,
              moneyline_result: 'Null',
              moneyline_stat: null,
              offerId: '0ab635f8-af84-5a28-b592-452158e1b6b6',
              teamId: null,
              playerId: '5984-nba',
              freeSquareId: null,
              created_at: new Date('2023-06-23T11:48:25.317Z'),
              updated_at: new Date('2023-06-23T11:48:25.317Z'),
              marketOverrideId: null,
              active: true,
              team: null,
              player: {
                id: '5984-nba',
                name: 'LeBron James',
                position: 'F',
                teamid: '11-nba',
                team: 'Los Angeles Lakers',
                headshot: null,
                Team: {
                  id: '11-nba',
                  name: 'Los Angeles',
                  code: 'LAL',
                },
              },
            },
          ],
        },
      ],
    },
  ],
  from: new Date(),
  to: new Date(),
  handleSaveEvent: () => console.log('handleSaveEvent'),
  isLoading: false,
  handleDeleteEvent: () => console.log('handleDeleteEvent'),
  handleSelectTournamentEvent: () => console.log('handleSelectTournamentEvent'),
  handleCopyEvent: () => console.log('handleCopyEvent'),
};
