/**
 * Adds seed data to your db
 *
 * @link https://www.prisma.io/docs/guides/database/seed-database
 */
import {
  AppSettingName,
  BetLegType,
  BetStatus,
  BetType,
  ContestType,
  ContestWagerType,
  League,
  MarketResult,
  MarketType,
  PrismaClient,
  Status,
  BetStakeType,
  ModuleName,
} from '@prisma/client';
import { appRouter } from '~/server/routers/_app';
import dayjs from 'dayjs';

import { faker } from '@faker-js/faker';
import { MORE_OR_LESS_CONTEST_ID } from '~/constants/MoreOrLessContestId';

const prisma = new PrismaClient();

const caller = appRouter.createCaller({} as any);

async function main() {
  let user = await prisma.user.findFirst();
  if (!user) {
    try {
      await caller.user.signUp({
        email: 'test@gmail.com',
        password: 'Password1!',
        confirmPassword: 'Password1!',
        username: 'testing',
        DOB: new Date(),
        phone: '12392342999',
        state: 'TX',
        referralCode: '',
      });
    } catch (e) {
      // If test user auth already exist, trigger login to populate user's table
      await caller.user.login({
        email: 'test@gmail.com',
        password: 'Password1!',
      });
    }

    user = await prisma.user.findFirst();
  }

  await prisma.$queryRaw`truncate "Contest" cascade;`;
  await prisma.$queryRaw`truncate "ContestEntry" cascade;`;
  await prisma.$queryRaw`truncate "Offer" cascade;`;
  await prisma.$queryRaw`truncate "Team" cascade;`;
  await prisma.$queryRaw`truncate "Player" cascade;`;
  await prisma.$queryRaw`truncate "Market" cascade;`;
  await prisma.$queryRaw`truncate "Bet" cascade;`;
  const contestEntry = {
    id: 'contest-id-entry',
    tokens: 1000,
    User: {
      connect: {
        id: user?.id,
      },
    },
  };
  await prisma.contest.create({
    data: {
      id: MORE_OR_LESS_CONTEST_ID,
      name: 'MORE OR LESS CONTEST',
      description: 'This is a more or less contest',
      isActive: true,
      startDate: dayjs().subtract(1, 'h').toDate(),
      endDate: dayjs().add(50, 'year').toDate(),
      type: ContestType.FANTASY,
      bgImageUrl: 'https://picsum.photos/200',
      entryFee: 200,
      totalPrize: 1000,
      created_at: new Date(),
      updated_at: new Date(),
      wagerType: ContestWagerType.CASH,
      ContestEntries: {
        create: contestEntry,
      },
      priority: 1,
    },
  });
  await prisma.contest.create({
    data: {
      id: faker.datatype.uuid(),
      name: 'Fantasy Contest',
      description: 'This is a fantasy contest',
      isActive: true,
      startDate: dayjs().add(1, 'd').toDate(),
      endDate: dayjs().add(10, 'day').toDate(),
      type: ContestType.FANTASY,
      bgImageUrl: 'https://picsum.photos/200',
      entryFee: 200,
      totalPrize: 1000,
      created_at: new Date(),
      updated_at: new Date(),
    },
  });

  const contestCategories = [
    {
      id: faker.datatype.uuid(),
      numberOfPicks: 2,
      allInPayoutMultiplier: 3,
      primaryInsuredPayoutMultiplier: 2,
      secondaryInsuredPayoutMultiplier: 0.5,
    },
    {
      id: faker.datatype.uuid(),
      numberOfPicks: 3,
      allInPayoutMultiplier: 5,
      primaryInsuredPayoutMultiplier: 2.5,
      secondaryInsuredPayoutMultiplier: 1.25,
    },
    {
      id: faker.datatype.uuid(),
      numberOfPicks: 4,
      allInPayoutMultiplier: 10,
      primaryInsuredPayoutMultiplier: 5,
      secondaryInsuredPayoutMultiplier: 1.25,
    },
  ];
  await prisma.contestCategory.createMany({
    data: contestCategories,
  });

  await prisma.appSettings.createMany({
    data: [
      {
        id: '39788884-d375-4b07-8f3f-33e93c2ad07e',
        name: AppSettingName.NUMBER_OF_PLAYERS_FREE_ENTRY,
        value: '3,4,5',
      },
      {
        id: 'b7e216ac-1385-4d48-957e-dceba59d2ea4',
        name: AppSettingName.STAKE_TYPE_FREE_ENTRY,
        value: 'ALL_IN',
      },
      {
        id: 'd35a7683-d8f7-45c1-8016-dc316fbe38ac',
        name: AppSettingName.BONUS_CREDIT_FREE_ENTRY_EQUIVALENT,
        value: '50',
      },
      {
        id: '6f6cd43a-a1cc-4410-8f9f-711df16ecb11',
        name: AppSettingName.MAX_MATCH_DEPOSIT_AMOUNT,
        value: '100',
      },
      {
        id: 'fb693e7b-2606-41d6-a5f6-22aaf203b91b',
        name: AppSettingName.DEPOSIT_AMOUNT_OPTIONS,
        value: '20,30,50,75,100,200',
      },
      {
        id: 'd3ed4f9b-917a-4835-aad4-8c698e9f0085',
        name: AppSettingName.RELOAD_BONUS_TYPE,
        value: 'FLAT',
      },
      {
        id: '43a9e385-69ec-436c-aefd-45578755cc7d',
        name: AppSettingName.RELOAD_BONUS_AMOUNT,
        value: '0',
      },
      {
        id: '395d37cc-589d-4ec1-bb8e-66ed23c48ffb',
        name: AppSettingName.MAX_RETENTION_BONUS,
        value: '50',
      },
      {
        id: 'f7945457-62e8-4e62-a7c1-921616e7b4b8',
        name: AppSettingName.RETENTION_BONUS_WEEKLY_CHANCE,
        value: '1',
      },
      {
        id: 'cf1cd5ce-39a5-4c52-8052-58b328b65c24',
        name: AppSettingName.RETENTION_BONUS_MATCH_MULTIPLIER,
        value: '1',
      },
      {
        id: '855e36b3-18c3-478e-bdc3-fbdef6ab2970',
        name: AppSettingName.REFERRAL_CREDIT_AMOUNT,
        value: '25',
      },
      {
        id: '93c39e59-ec55-47fd-893d-49bb28e3200c',
        name: AppSettingName.REFERRAL_CUSTOM_TEXT,
        value:
          'Refer a friend from the link or code in your profile and get $25 in bonus credit!',
      },
      {
        id: '98942746-a739-4215-9b95-5489d4d688ae',
        name: AppSettingName.MIN_MARKET_ODDS,
        value: '-150',
      },
      {
        id: 'b785e00e-2579-4929-b220-a25c5a17efd0',
        name: AppSettingName.MAX_MARKET_ODDS,
        value: '150',
      },
      {
        id: 'adaeb5e7-3f7d-49a1-9359-889c02c4f927',
        name: AppSettingName.CHALLENGE_PROMO_MESSAGE,
        value:
          'Pick 2-5 players. Predict if they will get MORE or LESS than their projection.',
      },
      {
        id: '3d7ac4b9-6825-4a85-b093-7d1941f0f332',
        name: AppSettingName.MIN_BET_AMOUNT,
        value: '1',
      },
      {
        id: 'd4684b3e-7238-41bb-9cdc-c3210f72877c',
        name: AppSettingName.MAX_BET_AMOUNT,
        value: '50',
      },
      {
        id: '91bb28ce-98a7-4949-bce8-77d5b703ed1b',
        name: AppSettingName.REPEAT_ENTRIES_LIMIT,
        value: '0',
      },
      {
        id: 'ad104794-4aef-47ad-9922-9d68c25e7506',
        name: AppSettingName.SIGNUP_FREE_ENTRY,
        value: '0',
      },
      {
        id: '2fd0f6bc-d95d-4baa-863d-32e847de4418',
        name: AppSettingName.MAX_DAILY_TOTAL_BET_AMOUNT,
        value: '',
      },
      {
        id: 'cfacffe7-1861-48fb-858d-ccee6c7bed9c',
        name: AppSettingName.WEEKLY_REFERRAL_MAX_AMOUNT_EARNED,
        value: '0',
      },
    ],
  });
  await prisma.banner.createMany({
    data: [
      {
        appSettingId: '6f6cd43a-a1cc-4410-8f9f-711df16ecb11',
        id: '18959aee-fd4a-4f9e-bad6-2a1766f2fcb5',
        text: 'LockSpread will match your first deposit up to $100!',
        priority: 1,
        created_at: new Date('2022-12-12 13:34:03+00'),
        updated_at: new Date('2022-12-12 13:34:06+00'),
      },
      {
        appSettingId: '855e36b3-18c3-478e-bdc3-fbdef6ab2970',
        id: 'a0183781-943b-4e72-ae28-6e6e62e0d0d9',
        text: 'Refer a friend from the link or code in your profile and get $25 in bonus credit!',
        priority: 2,
        created_at: new Date('2022-12-12 13:34:03+00'),
        updated_at: new Date('2022-12-12 13:34:06+00'),
      },
      {
        appSettingId: '395d37cc-589d-4ec1-bb8e-66ed23c48ffb',
        id: '321456',
        text: '$50 Withdrawal Bonus we will match your winnings up to $50 on your withdrawal page every week.',
        priority: 3,
        created_at: new Date('2022-12-12 13:34:03+00'),
        updated_at: new Date('2022-12-12 13:34:06+00'),
      },
    ],
  });
  await prisma.module.createMany({
    data: [
      {
        active: true,
        id: 'f295ab9a-c98d-4470-a067-1d676a7b2874',
        description: 'Insert bonus credit',
        urlPath: 'AdminPlayFreeBonusCredit',
        name: ModuleName.MANAGEMENT_INSERT_BONUS_CREDIT,
      },
      {
        active: true,
        id: '800c0b2d-483b-4f44-8a86-473c77b55c18',
        description: 'Manually enter offer and lines',
        urlPath: 'AdminOffer',
        name: ModuleName.MANAGEMENT_MANUALLY_ENTER_OFFER_LINES,
      },
      {
        active: true,
        id: '4a8a9779-7a2f-442c-a3dc-23cad027c1ca',
        description: 'Update User Limits',
        urlPath: 'AdminUserLimits',
        name: ModuleName.MANAGEMENT_UPDATE_USERS_LIMITS,
      },
      {
        active: true,
        id: 'c2e2493f-5b5a-4dd0-b4ed-710b91b3e3e7',
        description: 'Manage Global Content',
        urlPath: 'AdminGlobalContent',
        name: ModuleName.MANAGEMENT_CONTENT,
      },
      {
        active: true,
        id: '2d514721-5c24-48e7-a94c-722629ea47d6',
        description: 'Withdrawal Offer',
        urlPath: 'ManageWithdrawalOffer',
        name: ModuleName.MANAGEMENT_WITHDRAWAL_OFFER,
      },
      {
        active: true,
        id: 'c94a2554-b126-41cd-9404-e977ad98f02f',
        description: 'Add/Remove Free Square Promotions',
        urlPath: 'AdminManageFreeSquarePromotion',
        name: ModuleName.MANAGEMENT_ADD_REMOVE_FREE_SQUARE_PROMOTIONS,
      },
      {
        active: true,
        id: '655fc926-ffff-4911-960b-edc570afd062',
        description: 'Bonus Credit Limits',
        urlPath: 'BonusCreditLimits',
        name: ModuleName.MANAGEMENT_BONUS_CREDIT_LIMITS,
      },
      {
        active: true,
        id: 'f6528e45-6bee-4e77-8cd3-cce428ddb0bb',
        description: 'Send SMS',
        urlPath: 'SendSMS',
        name: ModuleName.MANAGEMENT_SEND_SMS,
      },
      {
        active: true,
        id: '819fa539-2b33-441e-a865-f9b9f909d9d1',
        description: 'Weekly Balance',
        urlPath: 'AdminWeeklyBalance',
        name: ModuleName.FIGURES_WEEKLY_BALANCE,
      },
      {
        active: true,
        id: '1e985668-8ef3-4fe5-93b6-1c66bcfb58d9',
        description: 'Line Exposure',
        urlPath: 'AdminLineExposure',
        name: ModuleName.FIGURES_LINE_EXPOSURES,
      },
      {
        active: true,
        id: 'dbbc4f5d-a24f-43a4-8e1d-6aa8ede8fdd0',
        description: 'Player Totals By Range',
        urlPath: 'PlayerTotals',
        name: ModuleName.FIGURES_PLAYER_TOTALS_BY_RANGE,
      },
      {
        active: true,
        id: '42c10d7f-65e3-4867-8bc3-0a497fdd9f37',
        description: 'Add/remove from the `amount available to withdraw`',
        urlPath: 'AdminWithdrawable',
        name: ModuleName.MANAGEMENT_AMOUNT_AVAILABLE_TO_WITHDRAW,
      },
      {
        active: true,
        id: '23b660bc-4ca8-431c-a237-d5ef4c401d60',
        description: 'Manage User Permissions',
        urlPath: 'ManageUserPermissions',
        name: ModuleName.MANAGEMENT_MANAGE_USER_PERMISSIONS,
      },
      {
        active: true,
        id: '3fff029f-03e8-4c28-8c3e-73deea7f3a8a',
        description: 'AppSettings',
        urlPath: 'AppSettings',
        name: ModuleName.MANAGEMENT_APPSETTINGS,
      },
      {
        active: true,
        id: '6e17c7ae-1984-4b49-96ec-df166779738a',
        description: 'View Picks by User',
        urlPath: 'ViewPicksByUser',
        name: ModuleName.FIGURES_VIEW_PICKS_BY_USER,
      },
      {
        active: false,
        id: '2d9e4a5b-d281-4e00-9f88-2054773588f6',
        description: 'Balance by User ID',
        urlPath: 'AdminUsersBalance',
        name: ModuleName.MANAGEMENT_BALANCE_BY_USER_ID,
      },
      {
        active: true,
        id: '089ebf19-6729-425a-b31d-9d48d3338339',
        description: 'Partner Referral Codes',
        urlPath: 'ManageAgentReferralCodes',
        name: ModuleName.MANAGEMENT_AGENT_REFERRAL_CODES,
      },
      {
        active: true,
        id: '76bc1e41-33c0-452e-961d-5c03cfaff97f',
        description: 'Settle Pending Picks',
        urlPath: 'AdminPendingBets',
        name: ModuleName.ACTION_DELETE_PICKS,
      },
      {
        active: true,
        id: '20acb23f-fda2-425b-9a34-e6444dcbeb9b',
        description: 'Add/Edit Users',
        urlPath: 'ManageUsers',
        name: ModuleName.MANAGEMENT_MANAGE_USERS,
      },
      {
        active: true,
        id: 'dff28284-5f34-41bd-826a-7783db081946',
        description: 'Add/Edit Partners & PAMS',
        urlPath: 'ManagePartnersPams',
        name: ModuleName.MANAGEMENT_PARTNERS_PAMS,
      },
      {
        active: true,
        id: '2a581a19-fc40-4be0-8420-5fd2b2946222',
        description: 'Bets',
        urlPath: 'AdminViewUsersBets',
        name: ModuleName.MANAGEMENT_VIEW_BETS,
      },
      {
        active: true,
        id: 'd6c859d4-0a91-415a-95ef-b642d737a06d',
        description: 'List Offers',
        urlPath: 'ListOffers',
        name: ModuleName.MANAGEMENT_LIST_OFFERS,
      },
      {
        active: true,
        id: '4c27b76f-2da7-4064-8df2-bc00cedfd7fa',
        description: 'TSEVO Billing by Range',
        urlPath: 'TsevoBilling',
        name: ModuleName.FIGURES_TSEVO_BILLING,
      },
    ],
  });

  const gamedate = dayjs().add(1, 'd');
  await prisma.team.createMany({
    data: [
      {
        id: `1544-ncaaf`,
        name: 'West Virginia',
        code: 'WVU',
      },
      {
        id: `1430-ncaaf`,
        name: 'Baylor',
        code: 'BAYLOR',
      },
    ],
  });
  await prisma.player.createMany({
    data: [
      {
        id: `530898-ncaaf`,
        name: 'Sam James',
        position: 'WR',
        teamid: `1544-ncaaf`,
        team: 'West Virginia',
      },
      {
        id: `530909-ncaaf`,
        name: 'Bryce FordWheaton',
        position: 'WR',
        teamid: `1544-ncaaf`,
        team: 'West Virginia',
      },
      {
        id: `533742-ncaaf`,
        name: 'Ben Sims',
        position: 'TE',
        teamid: `1544-ncaaf`,
        team: 'Baylor',
      },
      {
        id: `534184-ncaaf`,
        name: 'JT Daniels',
        position: 'QB',
        teamid: `1544-ncaaf`,
        team: 'West Virginia',
      },
      {
        id: `538718-ncaaf`,
        name: 'Kaden Prather',
        position: 'WR',
        teamid: `1544-ncaaf`,
        team: 'West Virginia',
      },
      {
        id: `539394-ncaaf`,
        name: 'Blake Shapen',
        position: 'QB',
        teamid: `1544-ncaaf`,
        team: 'Baylor',
      },
      {
        id: `554186-ncaaf`,
        name: 'Monaray Baldwin',
        position: 'WR',
        teamid: `1544-ncaaf`,
        team: 'Baylor',
      },
      {
        id: `558570-ncaaf`,
        name: 'Hal Presley',
        position: 'WR',
        teamid: `1544-ncaaf`,
        team: 'Baylor',
      },
      {
        id: `562565-ncaaf`,
        name: 'Richard Reese',
        position: 'RB',
        teamid: `1544-ncaaf`,
        team: 'Baylor',
      },
    ],
  });
  const offer = {
    gid: '57767',
    league: 'NCAAF' as League,
    gamedate: gamedate.format('DD/MM/YYYY'),
    epoch: gamedate.unix(),
    start_utc: gamedate.toISOString(),
    end_utc: gamedate.add(2, 'h').toISOString(),
    inplay: false,
    status: Status.Scheduled,
    matchup: 'BAYLOR @ WVU',
    gametime: gamedate.format('HH:MM:ss'),
    homeTeamId: `1544-ncaaf`,
    awayTeamId: `1430-ncaaf`,
  };
  await prisma.offer.create({
    data: offer,
  });
  const markets = [
    {
      id: '57767-220-554186',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Monaray Baldwin',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 64.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `554186-ncaaf`,
      sel_id: 554186,
    },
    {
      id: '57767-215-539394',
      type: 'PP' as MarketType,
      category: 'Passing Yards',
      offerId: '57767',
      name: 'Blake Shapen',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 225.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `539394-ncaaf`,
      sel_id: 539394,
    },
    {
      id: '57767-220-558570',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Hal Presley',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 38.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `558570-ncaaf`,
      sel_id: 558570,
    },
    {
      id: '57767-215-534184',
      type: 'PP' as MarketType,
      category: 'Passing Yards',
      offerId: '57767',
      name: 'JT Daniels',
      teamAbbrev: 'WVU',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 239.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `534184-ncaaf`,
      sel_id: 534184,
    },
    {
      id: '57767-220-530909',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Bryce Ford-Wheaton',
      teamAbbrev: 'WVU',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 76.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `530909-ncaaf`,
      sel_id: 530909,
    },
    {
      id: '57767-24',
      type: 'GP' as MarketType,
      category: 'Team Total',
      offerId: '57767',
      name: 'West Virginia',
      teamAbbrev: 'WVU',
      offline: true,
      spread: null,
      spread_odd: null,
      total: 24.5,
      over: -115,
      under: -115,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: `1544-ncaaf`,
      playerId: null,
      sel_id: 1544,
    },
    {
      id: '57767-24',
      type: 'GP' as MarketType,
      category: 'Team Total',
      offerId: '57767',
      name: 'Baylor',
      teamAbbrev: 'BAYLOR',
      offline: true,
      spread: null,
      spread_odd: null,
      total: 28.5,
      over: -115,
      under: -115,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: `1430-ncaaf`,
      playerId: null,
      sel_id: 1430,
    },
    {
      id: '57767-12',
      type: 'GP' as MarketType,
      category: '1Q Game Line',
      offerId: '57767',
      name: 'West Virginia',
      teamAbbrev: 'WVU',
      offline: true,
      spread: 0.5,
      spread_odd: -140,
      total: 10.5,
      over: -115,
      under: -115,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'One' as MarketResult,
      spread_stat: null,
      over_result: 'Zero' as MarketResult,
      under_result: 'One' as MarketResult,
      total_stat: null,
      moneyline_result: 'One' as MarketResult,
      moneyline_stat: null,
      teamId: `1544-ncaaf`,
      playerId: null,
      sel_id: 1544,
    },
    {
      id: '57767-8',
      type: 'GP' as MarketType,
      category: '1H Game Line',
      offerId: '57767',
      name: 'Baylor',
      teamAbbrev: 'BAYLOR',
      offline: true,
      spread: -1.5,
      spread_odd: -115,
      total: 27.5,
      over: -110,
      under: -110,
      moneyline: -145,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'One' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'One' as MarketResult,
      moneyline_stat: null,
      teamId: `1430-ncaaf`,
      playerId: null,
      sel_id: 1430,
    },
    {
      id: '57767-6',
      type: 'GM' as MarketType,
      category: 'Game Line',
      offerId: '57767',
      name: 'Baylor',
      teamAbbrev: 'BAYLOR',
      offline: true,
      spread: -3,
      spread_odd: -110,
      total: 55,
      over: -110,
      under: -110,
      moneyline: -160,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Zero' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'Zero' as MarketResult,
      moneyline_stat: null,
      teamId: `1430-ncaaf`,
      playerId: null,
      sel_id: 1430,
    },
    {
      id: '57767-12',
      type: 'GP' as MarketType,
      category: '1Q Game Line',
      offerId: '57767',
      name: 'Baylor',
      teamAbbrev: 'BAYLOR',
      offline: true,
      spread: -0.5,
      spread_odd: 110,
      total: 10.5,
      over: -115,
      under: -115,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Zero' as MarketResult,
      spread_stat: null,
      over_result: 'Zero' as MarketResult,
      under_result: 'One' as MarketResult,
      total_stat: null,
      moneyline_result: 'Zero' as MarketResult,
      moneyline_stat: null,
      teamId: `1430-ncaaf`,
      playerId: null,
      sel_id: 1430,
    },
    {
      id: '57767-6',
      type: 'GM' as MarketType,
      category: 'Game Line',
      offerId: '57767',
      name: 'West Virginia',
      teamAbbrev: 'WVU',
      offline: true,
      spread: 3,
      spread_odd: -110,
      total: 55,
      over: -110,
      under: -110,
      moneyline: 140,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'One' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'One' as MarketResult,
      moneyline_stat: null,
      teamId: `1544-ncaaf`,
      playerId: null,
      sel_id: 1544,
    },
    {
      id: '57767-8',
      type: 'GP' as MarketType,
      category: '1H Game Line',
      offerId: '57767',
      name: 'West Virginia',
      teamAbbrev: 'WVU',
      offline: true,
      spread: 1.5,
      spread_odd: -105,
      total: 27.5,
      over: -110,
      under: -110,
      moneyline: 125,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Zero' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'Zero' as MarketResult,
      moneyline_stat: null,
      teamId: `1544-ncaaf`,
      playerId: null,
      sel_id: 1544,
    },
    {
      id: '57767-225-562565',
      type: 'PP' as MarketType,
      category: 'Rushing Yards',
      offerId: '57767',
      name: 'Richard Reese',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 74.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `562565-ncaaf`,
      sel_id: 562565,
    },
    {
      id: '57767-229',
      type: 'GP' as MarketType,
      category: 'Score First',
      offerId: '57767',
      name: 'West Virginia',
      teamAbbrev: 'WVU',
      offline: true,
      spread: null,
      spread_odd: null,
      total: 0.5,
      over: -110,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'One' as MarketResult,
      under_result: 'Zero' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: `1544-ncaaf`,
      playerId: null,
      sel_id: 1544,
    },
    {
      id: '57767-220-538718',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Kaden Prather',
      teamAbbrev: 'WVU',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 58.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `538718-ncaaf`,
      sel_id: 538718,
    },
    {
      id: '57767-236-534184',
      type: 'PP' as MarketType,
      category: 'TD Passes',
      offerId: '57767',
      name: 'JT Daniels',
      teamAbbrev: 'WVU',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 1.5,
      over: -125,
      under: -115,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `534184-ncaaf`,
      sel_id: 534184,
    },
    {
      id: '57767-229',
      type: 'GP' as MarketType,
      category: 'Score First',
      offerId: '57767',
      name: 'Baylor',
      teamAbbrev: 'BAYLOR',
      offline: true,
      spread: null,
      spread_odd: null,
      total: 0.5,
      over: -120,
      under: -110,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Zero' as MarketResult,
      under_result: 'One' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: `1430-ncaaf`,
      playerId: null,
      sel_id: 1430,
    },
    {
      id: '57767-220-533742',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Ben Sims',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 37.5,
      over: -115,
      under: -125,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `533742-ncaaf`,
      sel_id: 533742,
    },
    {
      id: '57767-236-539394',
      type: 'PP' as MarketType,
      category: 'TD Passes',
      offerId: '57767',
      name: 'Blake Shapen',
      teamAbbrev: 'BAYLOR',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 1.5,
      over: -135,
      under: -105,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `539394-ncaaf`,
      sel_id: 539394,
    },
    {
      id: '57767-220-530898',
      type: 'PP' as MarketType,
      category: 'Receiving Yards',
      offerId: '57767',
      name: 'Sam James',
      teamAbbrev: 'WVU',
      offline: false,
      spread: null,
      spread_odd: null,
      total: 51.5,
      over: -120,
      under: -120,
      moneyline: null,
      spread_bet: null,
      spread_cash: null,
      over_bet: null,
      under_bet: null,
      over_cash: null,
      under_cash: null,
      moneyline_bet: null,
      moneyline_cash: null,
      spread_result: 'Null' as MarketResult,
      spread_stat: null,
      over_result: 'Null' as MarketResult,
      under_result: 'Null' as MarketResult,
      total_stat: null,
      moneyline_result: 'Null' as MarketResult,
      moneyline_stat: null,
      teamId: null,
      playerId: `530898-ncaaf`,
      sel_id: 530898,
    },
  ];
  await prisma.market.createMany({
    data: markets,
  });
  await prisma.bet.create({
    data: {
      id: '1',
      stake: 100,
      status: BetStatus.PENDING,
      owner: {
        connect: {
          id: user?.id,
        },
      },
      payout: 200,
      type: BetType.PARLAY,
      legs: {
        create: {
          id: 'leg1',
          market: {
            connect: {
              id_sel_id: {
                id: markets[0]!.id,
                sel_id: markets[0]!.sel_id,
              },
            },
          },
          type: BetLegType.OVER_ODDS,
          odds: 100,
          total: 100,
          status: BetStatus.PENDING,
        },
      },
      odds: 100,
      ContestEntries: {
        connect: {
          id: contestEntry.id,
        },
      },
      ContestCategory: {
        connect: {
          id: contestCategories[0]!.id,
        },
      },
      stakeType: BetStakeType.ALL_IN,
    },
  });
  await prisma.bet.create({
    data: {
      id: '2',
      stake: 100,
      status: BetStatus.WIN,
      owner: {
        connect: {
          id: user?.id,
        },
      },
      payout: 200,
      type: BetType.PARLAY,
      legs: {
        create: {
          id: 'leg2',
          market: {
            connect: {
              id_sel_id: {
                id: markets[0]!.id,
                sel_id: markets[0]!.sel_id,
              },
            },
          },
          type: BetLegType.OVER_ODDS,
          odds: 100,
          total: 100,
          status: BetStatus.WIN,
        },
      },
      odds: 100,
      ContestEntries: {
        connect: {
          id: contestEntry.id,
        },
      },
      ContestCategory: {
        connect: {
          id: contestCategories[0]!.id,
        },
      },
      stakeType: BetStakeType.ALL_IN,
    },
  });
  await prisma.bet.create({
    data: {
      id: '3',
      stake: 100,
      status: BetStatus.LOSS,
      owner: {
        connect: {
          id: user?.id,
        },
      },
      payout: 200,
      type: BetType.PARLAY,
      legs: {
        create: {
          id: 'leg3',
          market: {
            connect: {
              id_sel_id: {
                id: markets[0]!.id,
                sel_id: markets[0]!.sel_id,
              },
            },
          },
          type: BetLegType.OVER_ODDS,
          odds: 100,
          total: 100,
          status: BetStatus.LOSS,
        },
      },
      odds: 100,
      ContestEntries: {
        connect: {
          id: contestEntry.id,
        },
      },
      ContestCategory: {
        connect: {
          id: contestCategories[0]!.id,
        },
      },
      stakeType: BetStakeType.INSURED,
    },
  });
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
