export const picksCategoryLimitMock = {
  picksCategoryLimits: [
    {
      id: 'c2b4d6c7-f22c-4347-88bd-cee80ab06169',
      numberOfPicks: 2,
      allInPayoutMultiplier: 3.5,
      primaryInsuredPayoutMultiplier: 2,
      secondaryInsuredPayoutMultiplier: 0.5,
      customStakeLimitEnabled: false,
      minStakeAmount: 1,
      maxStakeAmount: 50,
    },
    {
      id: 'd78d68f7-e680-4f1f-b83d-2156f6fa28d8',
      numberOfPicks: 3,
      allInPayoutMultiplier: 5,
      primaryInsuredPayoutMultiplier: 2.5,
      secondaryInsuredPayoutMultiplier: 1.25,
      customStakeLimitEnabled: false,
      minStakeAmount: 1,
      maxStakeAmount: 50,
    },
    {
      id: '045e43ab-ef16-4ed5-9191-95edad4529a7',
      numberOfPicks: 4,
      allInPayoutMultiplier: 10,
      primaryInsuredPayoutMultiplier: 5,
      secondaryInsuredPayoutMultiplier: 1.25,
      customStakeLimitEnabled: false,
      minStakeAmount: 1,
      maxStakeAmount: 50,
    },
    {
      id: 'd2c27bdc-8688-4d9b-b982-da866098bb65',
      numberOfPicks: 5,
      allInPayoutMultiplier: 15,
      primaryInsuredPayoutMultiplier: 6,
      secondaryInsuredPayoutMultiplier: 2,
      customStakeLimitEnabled: false,
      minStakeAmount: 1,
      maxStakeAmount: 50,
    },
  ],
};
