/*
  Warnings:

  - The values [MANAGEMENT_MANAGE_USERS] on the enum `ModuleName` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "ModuleName_new" AS ENUM ('MANAGEMENT_INSERT_BONUS_CREDIT', 'MANAGEMENT_AMOUNT_AVAILABLE_TO_WITHDRAW', 'MANAGEMENT_MANUALLY_ENTER_OFFER_LINES', 'MANAGEMENT_BALANCE_BY_USER_ID', 'MANAGEMENT_UPDATE_USERS_LIMITS', 'MANAGEMENT_WITHDRAWAL_OFFER', 'MANAGEMENT_ADD_REMOVE_FREE_SQUARE_PROMOTIONS', 'MANAGEMENT_AGENT_REFERRAL_CODES', 'MANAGEMENT_BONUS_CREDIT_LIMITS', 'MANAGEMENT_SEND_SMS', 'MANAGEMENT_APPSETTINGS', 'MANAGEMENT_MANAGE_USER_PERMISSIONS', 'FIGURES_WEEKLY_BALANCE', 'FIGURES_LINE_EXPOSURES', 'FIGURES_PLAYER_TOTALS_BY_RANGE', 'ACTION_DELETE_PICKS');
ALTER TABLE "Module" ALTER COLUMN "name" TYPE "ModuleName_new" USING ("name"::text::"ModuleName_new");
ALTER TYPE "ModuleName" RENAME TO "ModuleName_old";
ALTER TYPE "ModuleName_new" RENAME TO "ModuleName";
DROP TYPE "ModuleName_old";
COMMIT;
